#-------------------------------------------------------------------------------------
# starship.toml - Kool prompt configuration.
# It has been tested with FiraCode Nerd font, with others you may have to change icons.
#-------------------------------------------------------------------------------------

"$schema" = 'https://starship.rs/config-schema.json'

format = """
\
[](fg:color_pill bg:none)\
$os\
[](fg:color_pill bg:color_uname_bg)\
$username\
[ ](fg:color_uname_bg bg:none)\
\
[](fg:color_pill bg:none)\
[ ](fg:color_black bg:color_pill)\
[](fg:color_pill bg:color_dir_bg)\
$directory\
[ ](fg:color_dir_bg bg:none)\
\
[](fg:color_pill bg:none)\
[ ](fg:color_black bg:color_pill)\
[](fg:color_pill bg:color_git_bg)\
$git_branch\
$git_status\
[ ](fg:color_git_bg bg:none)\
\
[](fg:color_pill bg:none)\
[ ](fg:color_black bg:color_pill)\
[](fg:color_pill bg:color_prg_bg)\
$c\
$rust\
$golang\
$python\
$zig\
[ ](fg:color_prg_bg bg:none)\
\
[](fg:color_pill bg:none)\
[ ](fg:color_black bg:color_pill)\
[](fg:color_pill bg:color_duration_bg)\
$cmd_duration\
[ ](fg:color_duration_bg bg:none)
\
$character
"""

palette = 'nando'

[palettes.nando]
color_pill = '#FFFFFF'		# white
color_os = '#000000'		# black
color_uname_fg = '#000000'	# black
color_uname_bg = '#B16286'	# purple
color_dir_fg = '#000000'	# black
color_dir_bg = '#D79921'	# yellow
color_git_fg = '#000000'	# black
color_git_bg = '#689D6A'	# aqua
color_root = '#CC241D'		# red
color_prg_fg = '#000000'	# black
color_prg_bg = '#D65D0E'	# orange
color_duration_fg = '#000000'	# black
color_duration_bg = '#CC241D'	# red
color_docker_fg = '#000000'	# black
color_docker_bg = '#458588'	# blue
color_fg1 = '#282828'
color_bg1 = '#343434'
color_bg3 = '#543B32'
color_black = '#000000'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#8EC07C'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#CC241D'
color_yellow = '#D79921'

[palettes.gruvbox]
color_fg0 = '#fbf1c7'
color_fg1 = '#282828'
color_bg1 = '#343434'
color_bg3 = '#543B32'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#8EC07C'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#CC241D'
color_yellow = '#D79921'

[palettes.breeze]
color_fg0 = '#deddda'
color_fg1 = '#282828'
color_bg1 = '#3C3836'
color_bg3 = '#8F6152'
color_blue = '#2980b9'
color_aqua = '#689d6a'
color_green = '#27ae60'
color_orange = '#f67400'
color_purple = '#926EE3'
color_red = '#da4453'
color_yellow = '#E8CB2D'

[palettes.gnome]
color_fg0 = '#ffffff'
color_fg1 = '#282828'
color_bg1 = '#3d3846'
color_bg3 = '#865e3c'
color_blue = '#1c71d8'
color_aqua = '#689d6a'
color_green = '#2ec27e'
color_orange = '#e66100'
color_purple = '#9E5EB8'
color_red = '#c01c28'
color_yellow = '#f5c211'

[palettes.default]
color_fg0 = '#ffffff'
color_fg1 = '#282828'
color_bg1 = '#3d3846'
color_bg3 = '#865e3c'
color_blue = '#0db7ed'
color_aqua = '#9AC338'
color_green = '#41FF00'
color_orange = '#B48350'
color_purple = '#7f3fbf'
color_red = '#c01c28'
color_yellow = '#FFE36C'

[os]
disabled = false
style = 'fg:color_os bg:color_pill'
format = '[$symbol]($style)'

[os.symbols]
Linux = " "
Macos = " "
Windows = " "

[username]
show_always = true
style_user = "bg:color_uname_bg fg:color_uname_fg"
style_root = "bg:color_uname_bg fg:color_root bold"
format = '[ $user ]($style)'

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "fg:color_dir_fg bg:color_dir_bg italic"
format = "[ $path ]($style)"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = "󰝚"
"Pictures" = ""
"Projects" = "󰲋"
"Videos" = ""

[git_branch]
symbol = ""
style = "fg:color_git_fg bg:color_git_bg"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:color_git_fg bg:color_git_bg"
format = '[($all_status$ahead_behind )]($style)'

# ------------------------------------------------
# PROGRAMMING LANGUAGES
# ------------------------------------------------

[c]
symbol = ""
style = "fg:color_prg_fg bg:color_prg_bg"
format = '[ $symbol( $version) ]($style)'

[golang]
#symbol = ""
symbol = "go"
style = "fg:color_prg_fg bg:color_prg_bg"
format = '[ $symbol( $version) ]($style)'

[java]
#symbol = ""
symbol = "java"
style = "fg:color_prg_fg bg:color_prg_bg"
format = '[ $symbol( $version) ]($style)'

[python]
#symbol = ""
symbol = "python"
style = "fg:color_prg_fg bg:color_prg_bg"
format = '[ $symbol( $version) ]($style)'

[rust]
#symbol = ""
symbol = "rust"
style = "fg:color_prg_fg bg:color_prg_bg"
format = '[ $symbol( $version) ]($style)'

[zig]
#symbol = ""
symbol = "zig"
version_format = "v${major}.${minor}.${patch}"
style = "fg:color_prg_fg bg:color_prg_bg"
format = '[ $symbol( $version) ]($style)'

[time]
disabled = true
time_format = "%l:%M %p"
style = "fg:color_fg0 bg:color_bg1"
format = '[ $time ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:color_green)'
error_symbol = '[❯](bold fg:color_red)'
vimcmd_symbol = '[❮](bold fg:color_green)'
vimcmd_replace_one_symbol = '[❮](bold fg:color_purple)'
vimcmd_replace_symbol = '[❮](bold fg:color_purple)'
vimcmd_visual_symbol = '[❮](bold fg:color_yellow)'

[cmd_duration]
disabled = false
show_milliseconds = false
min_time = 4
style = "bg:color_duration_bg fg:color_duration_fg"
format = "[ $symbol ($duration) ]($style)"

